version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dnd_postgres
    environment:
      POSTGRES_DB: dnd_game
      POSTGRES_USER: dnd_user
      POSTGRES_PASSWORD: dnd_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dnd_user -d dnd_game"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dnd_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: dnd_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  stable-diffusion:
    image: continuumio/miniconda3:latest
    container_name: dnd_stable_diffusion
    ports:
      - "7860:7860"
    volumes:
      - sd_data:/app/models
      - ./stable_diffusion:/app
    working_dir: /app
    command: >
      bash -c "
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 &&
        pip install diffusers transformers accelerate scipy safetensors &&
        pip install fastapi uvicorn pillow &&
        python sd_server.py
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  ollama_data:
  sd_data: